#!/usr/bin/env bun
/**
 * Generate src/version.ts with build-time metadata
 * Run automatically before builds via prebuild hook
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "child_process";

// Get script directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read version from package.json
const packageJsonPath = join(__dirname, "../package.json");
const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
const version = packageJson.version;

// Generate build timestamp
const buildDate = new Date().toISOString();

// Try to get git commit hash
let gitCommit: string | null = null;
try {
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: join(__dirname, ".."),
    encoding: "utf-8",
  });
  if (result.status === 0 && result.stdout) {
    gitCommit = result.stdout.trim();
  }
} catch (error) {
  // Git not available or not a git repo - that's okay
  console.warn("Warning: Could not detect git commit (git not available or not a git repo)");
}

// Generate version.ts content
const content = `// Auto-generated by scripts/generate-version.ts
// Do not edit manually - this file is generated during build

export const VERSION = "${version}";
export const BUILD_DATE = "${buildDate}";
export const IS_COMPILED = true;
export const GIT_COMMIT = ${gitCommit ? `"${gitCommit}"` : "null"};
`;

// Write to src/version.ts
const versionFilePath = join(__dirname, "../src/version.ts");
writeFileSync(versionFilePath, content, "utf-8");

console.log(`✓ Generated version.ts:`);
console.log(`  Version:    ${version}`);
console.log(`  Build Date: ${buildDate}`);
console.log(`  Git Commit: ${gitCommit || "not available"}`);
